# Generated by Django 3.2.7 on 2021-11-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('propiedadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=80)),
                ('imagenPrincipal', models.ImageField(null=True, upload_to='propiedades')),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=15)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numCuartos', models.IntegerField()),
                ('numBanos', models.IntegerField()),
                ('numCamas', models.IntegerField()),
                ('numHuespedMax', models.IntegerField()),
                ('estadiaMin', models.IntegerField()),
                ('disponibilidad', models.BooleanField()),
                ('conInternet', models.BooleanField()),
                ('permiteMascotas', models.BooleanField()),
                ('conEstacionamiento', models.BooleanField()),
                ('conCocina', models.BooleanField()),
                ('conSala', models.BooleanField()),
                ('conLavanderia', models.BooleanField()),
                ('conTvCable', models.BooleanField()),
                ('conAireAcondicionado', models.BooleanField()),
                ('otrasComodidades', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reservaID', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField()),
                ('fechaLlegada', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('estadoPago', models.BooleanField()),
                ('clasificacion', models.IntegerField()),
                ('resena', models.CharField(max_length=150)),
                ('descuento', models.DecimalField(decimal_places=1, max_digits=1)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlojamiento',
            fields=[
                ('tipoAlojamientoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipoDocumentoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('tipoPropiedadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeoID', models.AutoField(primary_key=True, serialize=False)),
                ('codigoPostal', models.CharField(max_length=8)),
                ('distrito', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=30)),
                ('sexo', models.BooleanField()),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('imagenPerfil', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('pais', models.CharField(max_length=30)),
                ('numeroDocumento', models.CharField(max_length=12)),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('transaccionID', models.AutoField(primary_key=True, serialize=False)),
                ('nroComprobante', models.CharField(max_length=12)),
                ('fechaTransaccion', models.DateField()),
                ('horaTransaccion', models.TimeField()),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montoPago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montoDescuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.usuario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipoAlojamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.tipoalojamiento'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipoPropiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.tipopropiedad'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.ubigeo'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.usuario'),
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('imagenID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='articulos')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.propiedad')),
            ],
        ),
    ]
