# Generated by Django 3.2.7 on 2021-11-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='tipoAlojamiento',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tipoPropiedad',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='ubigeo',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipoDocumento',
        ),
        migrations.DeleteModel(
            name='ImagenPropiedad',
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='TipoAlojamiento',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
        migrations.DeleteModel(
            name='TipoPropiedad',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.DeleteModel(
            name='Ubigeo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
