# Generated by Django 3.2.7 on 2021-11-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Tipo Propiedad',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('propiedadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('ciudad', models.CharField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(max_length=140)),
                ('numCuartos', models.IntegerField()),
                ('numMaxHuspedes', models.IntegerField()),
                ('numCamas', models.IntegerField()),
                ('numBano', models.IntegerField()),
                ('conInternet', models.BooleanField()),
                ('permiteMascotas', models.BooleanField()),
                ('conEstacionamiento', models.BooleanField()),
                ('conCocina', models.BooleanField()),
                ('conSala', models.BooleanField()),
                ('conLavanderia', models.BooleanField()),
                ('conTvCable', models.BooleanField()),
                ('conAireAcondicionado', models.BooleanField()),
                ('otrasComodidades', models.CharField(max_length=200, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('reserva_instantanea', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Propiedads', to=settings.AUTH_USER_MODEL)),
                ('tipoPropiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Propiedades', to='propiedades.tipopropiedad')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='FotosPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('archivo', models.ImageField(upload_to='propiedad_fotos')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='propiedades.propiedad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
