# Generated by Django 3.2.7 on 2021-11-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_remove_propiedad_reserva_instantanea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='check_out',
        ),
    ]
